site_name: Sculk
site_description: Documentation for Sculk, a program for creating Minecraft modpacks.
site_url: https://sculk-cli.github.io
site_author: The Sculk Team

repo_url: https://github.com/sculk-cli/sculk-cli.github.io
repo_name: sculk-cli/sculk-cli.github.io

extra_css:
  - stylesheets/extra.css

nav:
  - Welcome: index.md
  - "How It Works": how-it-works.md
  - Guides:
      - "Getting Started": guides/getting-started.md
      - "Finding Mods Using the Userscript": guides/finding-mods-using-the-userscript.md
      - "Installing from GitHub": guides/installing-from-github.md
      - "Checking with GitHub Actions": guides/checking-with-github-actions.md
  - Commands:
      - Completion: commands/completion.md
      - Init: commands/init.md
      - Install: commands/install.md
      - Modlist: commands/modlist.md
      - Refresh: commands/refresh.md
      - Remove: commands/remove.md
      - Add:
          - Curseforge: commands/add/curseforge.md
          - Modrinth: commands/add/modrinth.md
          - URL: commands/add/url.md
          - List: commands/add/list.md
      - Export:
          - Curseforge: commands/export/curseforge.md
          - Modrinth: commands/export/modrinth.md
      - Import:
          - Curseforge: commands/import/curseforge.md
          - Modrinth: commands/import/modrinth.md
  - "Manifest Format":
      - "manifest.sculk.json": manifest-format/manifest-sculk-json.md
      - "dependency-graph.sculk.json": manifest-format/dependency-graph-sculk-json.md
      - "Manifest File": manifest-format/manifest-file.md

theme:
  name: material
  logo: assets/sculk-icon.png
  favicon: assets/sculk-icon.png
  language: en

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.share
    - content.code.annotate

  palette:
    scheme: default
    primary: custom
    accent: red

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: timeago

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - sane_lists

extra:
  homepage: https://github.com/sculk-cli

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.jamalam.tech
    - icon: fontawesome/brands/github
      link: https://github.com/sculk-cli
    - icon: fontawesome/solid/dollar-sign
      link: https://ko-fi.com/jamalamdev
